#本插件需要papi,请先在服务器内输入/papi ecloud download Server和/papi ecloud download Player
version: 1.4
local: "null"
#这个版本文件请不要乱改！！！！
message-reload: ' 插件重载成功'
message-upload: ' 祝福上传成功'
message-di: ' 第'
message-is: '个人的祝福是：'
message-error: ' 语法错误'
message-list: ' 祝福列表'
message-already: ' 你已经写过祝福了'
message-no: '你没有权限这么做'
message-notime: ' 现在不是祝福月'
message-front: '[NewYearBlessing]'
message-nohd: '未发现hd插件，全息功能关闭'
#以上是一些语言文件
use-month: '1'
#玩家许愿成功后执行的指令，支持papi
reward:
  enable: false
  commands:
    - "give {player} diamond"
lottery:
  enable: false
  commands:
    - "give {player} diamond 64"
Blessing: