name: NewyearBlessing
version: 1.4
main: newyearblessing.newyearblessing.NewyearBlessing
api-version: 1.15
commands:
  nyb:
    description: 主指令
permissions:
  newyearblessing.command.reload:
    description: 重载插件的权限
    default: op
  newyearblessing.command.createhd:
    description: 创建全息权限
    default: op
  newyearblessing.command.deletehd:
    description: 删除全息权限
    default: op
  newyearblessing.command.lottery:
    description: 抽奖权限
    default: op